version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "270514764245"
    DOCKER_PASSWORD: "Myfirstpwd@2024"
    DOCKER_USERNAME: "harishatomedgesoft"
    ECR_REGISTRY: "270514764245.dkr.ecr.us-east-1.amazonaws.com/aura-postgres"

phases:
  install:
    commands:
      - echo "Installing dependencies"
      - sudo apt update -y
      - sudo apt install -y docker.io
      - docker --version
      - pip install awscli
      - aws --version
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - echo "Logging in to Amazon ECR"
      - echo "$AWS_DEFAULT_REGION"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | sudo docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image"
      - docker build -t aura-postgres .
      - docker tag aura-postgres:devops $ECR_REGISTRY
  post_build:
    commands:
      - echo "Pushing the Docker image"
      - docker push $ECR_REGISTRY
artifacts:
  files:
    - '**/*'
